version: '3'
services:
  scraper:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - browserLimit=20
      - timeOut=30000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
